kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux
    command: ["sleep","100"]
    env:
      - name: course
        valueFrom:
          ConfigMapKeyRef:
            name: nginx-config
            key: course
      - name: duration
        valueFrom:
          ConfigMapKeyRef:
            name: nginx-config
            key: duration