apiVersion: v1
kind: Secrets
metadata:
  name: nginx
spec:
  selectors:
    project: expense
    module: backend
    environment: dev
  ports:
    - name: nginx-svc-ports
      protocol: TCP
      port: 80
      target: 80