apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    project: expense
    moodule: backend
    environment: dev
  ports:
    - name: nginx-svc-ports
      protocol: TCP
      port: 80 #(default: 30000-32767)
      targetPort: 80


      # kubectl patch svc nginx -p '{"spec": {"type": "NodePort"}}'  ---patch to node which you what
